### ISSUE TITLE
Config manaement

### ISSUE THREAD

**Issue by luqasz** [napalm-automation-community/napalm-ros#40]
Hi.

Since MikroTik does not have any notion of `config replace`, I was wandering how to solve this problem in driver. I've [done](https://github.com/luqasz/mcm) config management from parsed JSON file. This works well if you specify every option. 

Do you have any other ideas ?

**Comment by dbarrosop** [comment]
Could you show some example?

**Comment by luqasz** [comment]
https://github.com/luqasz/mcm/wiki/Getting-Started

**Comment by dbarrosop** [comment]
So, the problem with the solution described there is you have to know what to remove, right? The library doesn't know unless you specify it, does it?

**Comment by luqasz** [comment]
Yes. Same goes to imports from cli.

**Comment by dbarrosop** [comment]
Mmm, I think it defeats the purpose of the `replace` function, if you know what to remove and you have to specify it, that's more of a `merge` operation.

**Comment by luqasz** [comment]
`replace()` may raise `NotImplemented` because it it not possible.

**Comment by dbarrosop** [comment]
For any module not implemented, you can just leave it out. The base class has them all and it raises a NotImplemented exception already.

**Comment by adamharm** [comment]
I am interested in helping implement some configuraton management in this library.  I have limited experience with napalm and so I would appreciate some pointers to get me started.

Am I correct in assuming that configuration merge is the way we need to go because mikrotiks don't support a way to replace the running configuration?

Are you aware if others drivers have had to resolve this same issue so I can look at their code to see how they achieved it?

Any other pointers would be great as I want to get started on this asap.

**Comment by luqasz** [comment]
@adamharm please contact me on offifial NAPALM [slack](https://networktocode.herokuapp.com/). I will help you and we can discuss this topic there.

**Comment by luqasz** [comment]
closing in favor of #71
